version = 1
SPDX-PackageName = "mdcommands"
SPDX-PackageSupplier = "Keith Maxwell <keith.maxwell@gmail.com>"
SPDX-PackageDownloadLocation = "https://github.com/maxwell-k/mdcommands"

[[annotations]]
path = [
  ".en.utf-8.add",
  ".gitignore",
  "deno.json",
  "deno.lock",
]
SPDX-FileCopyrightText = "2025 Keith Maxwell <keith.maxwell@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["__snapshots__/main_test.ts.snap"]
SPDX-FileCopyrightText = "2025 Keith Maxwell <keith.maxwell@gmail.com>"
SPDX-License-Identifier = "MPL-2.0"

# REUSE.toml
# Copyright Keith Maxwell
# SPDX-License-Identifier: CC0-1.0
