# .github/workflows/commitlint.yaml
# Copyright 2025 Keith Maxwell
# SPDX-License-Identifier: CC0-1.0

on: # yamllint disable-line rule:truthy
  pull_request: { branches: [main] }
  workflow_dispatch:

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - run:
          podman run "--volume=$PWD:/src:z" --workdir=/src commitlint/commitlint
          --verbose --from=origin/main --to=HEAD
