# .github/workflows/test.yaml
# Copyright 2024 Keith Maxwell
# SPDX-License-Identifier: CC0-1.0

on: # yamllint disable-line rule:truthy
  push: { branches: [main] }
  pull_request: { branches: [main] }
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
      - run: rm deno.lock # to also check the lock file is up to date
      - run: deno task test
      - run: git diff --exit-code # changes cause this job to fail
      - uses: actions/upload-artifact@v4
        with: { path: coverage/html/ }
